version: "3.8"
services:
  service_name:
    build:
      context: .
      dockerfile: Dockerfile
    command: "php artisan serve --host=0.0.0.0"
    volumes:
      - .:/app
    ports:
      - 8001:8000
    depends_on:
      - service_name

  service_name_queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: "php artisan queue:work"
    depends_on:
      - service_name

  billing_service:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: your_db
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
      MYSQL_ROOT_PASSWORD: your_password
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33061:3306
    networks:
      - mysql-phpmyadmin

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - service_name
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: service_name
      MYSQL_ROOT_PASSWORD: your_password
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:
